# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  },
  :slave => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|
config.vbguest.auto_update = false
config.vm.synced_folder ".", "/vagrant", disabled: true
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            timedatectl set-timezone Europe/Moscow
            SHELL
      end
  end
config.vm.define 'master' do |master|
      master.vm.provision "shell", inline: <<-SHELL
sudo su
cd /root
sudo yum install redhat-lsb-core wget rpmdevtools rpm-build createrepo yum-utils gcc libtool doxygen libuuid-devel -y
wget http://nginx.org/packages/centos/7/SRPMS/nginx-1.14.2-1.el7_4.ngx.src.rpm
rpm -i nginx-1.14.2-1.el7_4.ngx.src.rpm
wget https://www.openssl.org/source/latest.tar.gz
tar -xvf latest.tar.gz
sed -i '110c\--with-openssl=/root/openssl-1.1.1b' /root/rpmbuild/SPECS/nginx.spec
yum-builddep /root/rpmbuild/SPECS/nginx.spec -y
rpmbuild -bb /root/rpmbuild/SPECS/nginx.spec
yum localinstall -y /root/rpmbuild/RPMS/x86_64/nginx-1.14.2-1.el7_4.ngx.x86_64.rpm -y
systemctl start nginx
yum remove apr -y
wget http://mirror.linux-ia64.org/apache/apr/apr-1.7.0.tar.bz2
rpmbuild -tb /root/apr-1.7.0.tar.bz2
yum localinstall -y /root/rpmbuild/RPMS/x86_64/apr-1.7.0-1.x86_64.rpm
yum localinstall -y /root/rpmbuild/RPMS/x86_64/apr-devel-1.7.0-1.x86_64.rpm
yum install apr-util-devel -y
wget http://mirror.linux-ia64.org/apache/httpd/httpd-2.4.38.tar.bz2
rpmbuild -ts httpd-2.4.38.tar.bz2
rpm -i /root/rpmbuild/SRPMS/httpd-2.4.38-1.src.rpm
sed -i '113a\%package -n mod_session' /root/rpmbuild/SPECS/httpd.spec
sed -i '114a\Summary: Session interface for the Apache HTTP Server' /root/rpmbuild/SPECS/httpd.spec
sed -i '115a\Requires: httpd = 0:%{version}-%{release}, httpd-mmn = %{mmn}' /root/rpmbuild/SPECS/httpd.spec
sed -i '116a\ \n' /root/rpmbuild/SPECS/httpd.spec
sed -i '117a\%description -n mod_session' /root/rpmbuild/SPECS/httpd.spec
sed -i '118a\The mod_session module and associated backends provide an abstract' /root/rpmbuild/SPECS/httpd.spec
sed -i '119a\interface for storing and accessing per-user session data.' /root/rpmbuild/SPECS/httpd.spec
sed -i '120a\ \n' /root/rpmbuild/SPECS/httpd.spec
sed -i '397d' /root/rpmbuild/SPECS/httpd.spec
sed -i '485a\%files -n mod_session' /root/rpmbuild/SPECS/httpd.spec
sed -i '486a\%defattr(-,root,root)' /root/rpmbuild/SPECS/httpd.spec
sed -i '487a\%{_libdir}/httpd/modules/mod_session.so' /root/rpmbuild/SPECS/httpd.spec
sed -i '488a\%{_libdir}/httpd/modules/mod_auth_form.so' /root/rpmbuild/SPECS/httpd.spec
sed -i '489a\ \n' /root/rpmbuild/SPECS/httpd.spec
yum-builddep /root/rpmbuild/SPECS/httpd.spec -y
rpmbuild -bb rpmbuild/SPECS/httpd.spec
mkdir /usr/share/nginx/html/repo
cp /root/rpmbuild/RPMS/x86_64/* /usr/share/nginx/html/repo
createrepo /usr/share/nginx/html/repo/
sed -i '11a\ autoindex on;' /etc/nginx/conf.d/default.conf
nginx -t
nginx -s reload
SHELL
end

config.vm.define 'slave' do |slave|
      slave.vm.provision "shell", inline: <<-SHELL
echo '[otus]\nname=otus-linux\nbaseurl=http://192.168.11.150/repo\ngpgcheck=0\nenabled=1'>/etc/yum.repos.d/otus.repo
SHELL
end
end
